In [ ]:
# File: homework6

In [ ]:
# 3 - Numpy Arrays

In [55]:
import numpy as np

In [56]:
# 3.1 - 1D NumPy Arrays

In [57]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

In [58]:
# Multiply by 4
print("Array multiplied by 4:", arr * 4)

Array multiplied by 4: [ 80 108  36  48 124  68  16 200 156 140]


In [59]:
# Mean, median, and standard deviation
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 24.4
Median: 23.5
Standard Deviation: 13.828955130450023


In [60]:
# Index of smallest and largest numbers
print("Index of smallest:", np.argmin(arr))
print("Index of largest:", np.argmax(arr))

Index of smallest: 6
Index of largest: 7


In [61]:
# Corresponding values
print("Smallest value:", arr[np.argmin(arr)])
print("Largest value:", arr[np.argmax(arr)])

Smallest value: 4
Largest value: 50


In [63]:
# smallest and largest
print("np.min:", np.min(arr))
print("np.max:", np.max(arr))

np.min: 4
np.max: 50


In [64]:
# Values greater than 20
print("Values greater than 20:", arr[arr > 20])


Values greater than 20: [27 31 50 39 35]


In [65]:
# 3.2 - 2D NumPy Arrays

In [66]:
matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])

In [67]:
# Shape
print("Shape:", matrix.shape)

Shape: (3, 4)


In [68]:
# Third column and second row
print("Third column:", matrix[:, 2])
print("Second row:", matrix[1])

Third column: [17 14 19]
Second row: [ 8 21 14  3]


In [69]:
# Multiply all elements by 2
print("Matrix * 2:\n", matrix * 2)

Matrix * 2:
 [[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [70]:
# Mean of each column
print("Column means:", np.mean(matrix, axis=0))

Column means: [ 6.33333333 15.33333333 16.66666667  7.66666667]


In [71]:
# Overall mean
print("Overall mean:", np.mean(matrix))

Overall mean: 11.5


In [72]:
# Max per row, min per column
print("Max of each row:", np.max(matrix, axis=1))
print("Min of each column:", np.min(matrix, axis=0))

Max of each row: [17 21 19]
Min of each column: [ 5 12 14  3]


In [74]:
# Flatten
flat = matrix.flatten()
print("Flattened array:", flat)
print("New shape:", flat.shape)
# It makes it into a 1D array

Flattened array: [ 5 12 17  9  8 21 14  3  6 13 19 11]
New shape: (12,)


In [75]:
min_idx = np.argmin(flat)
max_idx = np.argmax(flat)
print("Flat index of min:", min_idx)
print("Flat index of max:", max_idx)
print("Unraveled min index:", np.unravel_index(min_idx, matrix.shape))
print("Unraveled max index:", np.unravel_index(max_idx, matrix.shape))

Flat index of min: 7
Flat index of max: 5
Unraveled min index: (np.int64(1), np.int64(3))
Unraveled max index: (np.int64(1), np.int64(1))


In [76]:
# Values > 15
print("Values > 15:", matrix[matrix > 15])

Values > 15: [17 21 19]


In [77]:
# Sort
print("Sorted rows:\n", np.sort(matrix, axis=1))

Sorted rows:
 [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [78]:
# 4 - Prime Star Systems

In [79]:
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

In [80]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

In [81]:
def prime_star_systems(arr):
    mask = np.array([any(is_prime(x) for x in row) for row in arr])
    return arr[mask]

In [82]:
print("Rows with at least one prime:\n", prime_star_systems(arr))

Rows with at least one prime:
 [[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [83]:
# 5 - Checkers

In [84]:
def empty_board():
    board = np.zeros((8, 8), dtype=int)
    return board
    
print(empty_board())

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [85]:
def partial_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    # Fill only odd-numbered rows (1, 3, 5, 7)
    for i in range(1, 8, 2):
        board[i, 1::2] = 1  # pattern starting with 1
    return board

print(partial_checkerboard())

[[0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]]


In [86]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, ::2] = 1  # even rows start with 1
    board[1::2, 1::2] = 1  # odd rows shifted pattern
    return board

print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [87]:
def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, 1::2] = 1  # even rows start with 0
    board[1::2, ::2] = 1  # odd rows shifted pattern
    return board

print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [88]:
#6 - The Expanding Universe

In [89]:
def expansion(arr, n):
    expanded = np.array([' '.join(word[i] for i in range(len(word))).replace(' ', ' ' * (n + 1)) for word in arr])
    return expanded

In [90]:
universe = np.array(['galaxy', 'clusters'])
print("Expansion with 1 space:\n", expansion(universe, 1))
print("Expansion with 2 spaces:\n", expansion(universe, 2))

Expansion with 1 space:
 ['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']
Expansion with 2 spaces:
 ['g   a   l   a   x   y' 'c   l   u   s   t   e   r   s']


In [91]:
# 7 - Second-Brightest Star

In [93]:
def secondDimmest(stars):
    sorted_rows = np.sort(stars, axis=1)[:, ::-1]
    return sorted_rows[:, 1]

In [94]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print("Stars array:\n", stars)
print("Second brightest in each cluster:\n", secondDimmest(stars))

Stars array:
 [[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
Second brightest in each cluster:
 [1889 1647 1138 1863 1592]
